### ISSUE TITLE
Add inline code samples documentation for missing modules

### ISSUE THREAD

**Issue by depombo** [iasql/iasql#1622]
https://github.com/jbreckmckye/testdoc looks like it might hold potential. https://github.com/jbreckmckye/testdoc/blob/master/src/api.ts#L16-L34 is the key bit. It's very fixed function, but it's internals look pretty clean, so I think we could use them directly. Parse with the typescript parser, grab the AST directly and generate our own markdown

**Comment by yrobla** [comment]
My idea would be to reuse the current plugin that we are using for documentation and add those queries , to replace the current @example ones that we do manually. We could have a custom annotation where we pass the reference to the lines of code to use, and generate the snippet for us.
