### ISSUE TITLE
Integrate Lambda with `code*` modules and dogfood

### ISSUE THREAD

**Issue by depombo** [iasql/iasql#1787]

**Comment by depombo** [comment]
@yrobla once you are done with current tasks, this is a good candidate!

**Comment by yrobla** [comment]
i added support to codedeploy, but we miss lambda function versioning , so i cannot properly fill the AppSpec: https://docs.aws.amazon.com/codedeploy/latest/userguide/reference-appspec-file-structure-resources.html

I can also add support for codepipeline. I good approach is https://awstip.com/ci-cd-pipeline-to-deploy-nodejs-code-to-aws-lambda-functions-on-aws-60c21719fb03
