### ISSUE TITLE
Implement DHCPOptions, InternetGateway, NetworkAcl for EC2

### ISSUE THREAD

**Issue by depombo** [iasql/iasql#1788]
- [x] Internet Gateway: https://github.com/iasql/iasql-engine/pull/1795 @mtp1376 
- [x] DHCPOptions
- [ ] NetworkACL
- [ ] Elastic Network Interface

**Comment by mtp1376** [comment]
@depombo should we also add ENI?

**Comment by depombo** [comment]
> @depombo should we also add ENI?

https://discord.com/channels/920684574231646229/949065192275316736/1065663741011693568

**Comment by depombo** [comment]
@mtp1376 / @aguillenv which are missing for this task ?

**Comment by mtp1376** [comment]
> @mtp1376 / @aguillenv which are missing for this task ?

All except the InternetGateway.

**Comment by yrobla** [comment]
will start working on DHCP options

**Comment by yrobla** [comment]
will continue with NetworkACL
