### ISSUE TITLE
Add Signature For RPC Functions

### ISSUE THREAD

**Issue by mtp1376** [iasql/iasql#1794]
Currently we don't have the exact signature for RPC functions as they all receive `VARIADIC _args text[] DEFAULT ARRAY[]::text[]` as the input. We might want to add the exact signature since it is more convenient to use by tools like DataGrip.

**Comment by dfellis** [comment]
The other advantage of adding the args that way would be stronger typing on the inputs :)

**Comment by mtp1376** [comment]
@depombo I'm interested in taking this task. Maybe we can have it in the next sprint?

**Comment by depombo** [comment]
> @depombo I'm interested in taking this task. Maybe we can have it in the next sprint?

Yes, go for it !
