### ISSUE TITLE
`apply` doesn't run outside of a transaction

### ISSUE THREAD

**Issue by depombo** [iasql/iasql#1853]

**Comment by depombo** [comment]
I created an ec2 instance outside a transaction and it seemed to work, but even after waiting for a while the instance id never gets populated. However, in a transaction it fills it in

**Comment by aguillenv** [comment]
did you run any other command while waiting for the instance to be created?

**Comment by aguillenv** [comment]
I was not able to replicate this. I've tried the following and both worked:

![Image](https://user-images.githubusercontent.com/5898639/214536709-51e35a82-dc04-4e9f-a162-e91a6568ea2c.png)

After ~2 minutes (the cron job runs every 2 min so it would depend on when you did the insert)

![Image](https://user-images.githubusercontent.com/5898639/214536883-73e80aea-407e-4ecb-b3d1-d9e858ce27de.png)

Then I tried to do an insert without a transaction and then run a transaction to see if that could be leaving it outside, but no, it is working:

![Image](https://user-images.githubusercontent.com/5898639/214537099-0ecbb033-f6f7-44fd-b91e-a67bb9205b80.png)

Instances 2 and 3 are there after the commit:

![Image](https://user-images.githubusercontent.com/5898639/214537193-b90c359e-cacd-4f42-8b0c-6268e46de7c7.png)

**Comment by depombo** [comment]
I also wasn't able to replicate
