### ISSUE TITLE
Make `upgrade` atomic to avoid db corruptions

### ISSUE THREAD

**Issue by depombo** [iasql/iasql#1871]
a better potential upgrade is:
1. create a new database with a new name, but provide the current user and group assigned to the older database to the connect logic so that user is associated with it.
2. query out the relevant info to re-install the needed modules and copy over the aws_credentials and aws_regions flags
3. install everything and be sure it's working
4. rename the old database to something else but "recoverable" (perhaps simply old_234242df...), then rename the new database to the old databases' name
5. finally drop the old database.
then we can have an extra check at the beginning that does two things: looks for databases that are in the iasql_databases table but don't actually exist, and databases that exist but aren't in iasql_databases. If one of the unlisted databases is old_... and there's a match in the iasql_databases list without the old prefix, we rename it back and remove it from both lists. If there is a match in the iasql_databases list we leave it alone, and then we delete all databases that shouldn't be there and then do the upgrade. This would allow us to have upgrades be interruptable without corruption
it also doesn't require that Step 1 preprocessing and file creation, just a very simple Step 2-equivalent to perform this check and then the Step 3-equivalent would be the upgrade sequence I just described here

**Comment by dfellis** [comment]
Closed by #1892
