### ISSUE TITLE
Add system metrics and dashboard

### ISSUE THREAD

**Issue by depombo** [iasql/iasql#1874]
Alternatives:
- cloudwatch metrics
- datadog (we should drop mezmo/logdna if we do this)
- statsd + grafana
- chronosphere

**Comment by depombo** [comment]
https://signoz.io is also considered a common open source datadog alternative

**Comment by aguillenv** [comment]
Initially added cloudwatch agent to staging with its dashboard

**Comment by aguillenv** [comment]
Metrics with cloud watch agent were added to production too
