### ISSUE TITLE
Normalize IAM JSON policies to facilitate comparison

### ISSUE THREAD

**Issue by depombo** [iasql/iasql#1997]

**Comment by depombo** [comment]
https://github.com/iasql/iasql/blob/main/src/services/aws-diff.ts is not working as expected

**Comment by depombo** [comment]
https://github.com/iasql/iasql/blob/main/test/common/aws-diff.ts

**Comment by mtp1376** [comment]
https://steampipe.io/blog/normalizing-aws-iam-policies-for-automated-analysis
https://github.com/turbot/steampipe-plugin-aws/blob/main/aws/canonical_policy.go

**Comment by mtp1376** [comment]
This is needed for `aws_sqs` mapper to avoid an infinite loop on policy change.
