### ISSUE TITLE
Add docker image size in PR comment and try to keep track of it

### ISSUE THREAD

**Issue by depombo** [iasql/iasql#2001]

**Comment by aguillenv** [comment]
For this we could do the following:
- [List the comments](https://docs.github.com/en/rest/issues/comments?apiVersion=2022-11-28#list-issue-comments) of the PR
- if comment exists, [update it](https://docs.github.com/en/rest/issues/comments?apiVersion=2022-11-28#update-an-issue-comment)
- if not create a new one as it is doing it now.
