### ISSUE TITLE
Reducing the size of the docker image further

### ISSUE THREAD

**Issue by depombo** [iasql/iasql#2023]
- Move next.js to production build

**Comment by dfellis** [comment]
Ideas to reduce it:

1. Run the Next.js build logic for each environment (and twice for `local` with and without telemetry enabled) and copy them into different directories running only the production build that matches the selected environment. Can reduce the amount of modules in `node_modules` and `node_modules` can be symlinked between all of them, which should make space usage a bit lower and speed up time-to-start for the dashboard at the cost of build complexity.
2. Figure out which `locale` in the `locales-all` meta-package we *actually* need for Postgres to have utf8 support and only install that one, which should save ~200MB
3. Find Debian packages that are installed but not actually used by any of our code and remove them, even if normally installed (like the package for `top`, though that one *is* already removed) and trim some of the ~300MB of OS deps.
4. Reduce `node_module` duplication by having the engine and dashboard use the same `node_module` pool, potentially reducing up to ~200MB
5. Explore using a base OS that's designed to be slimmer like Alpine Linux
6. Rewrite all of the bash scripts into Node.js scripts so all of the bash utilities we use like `jq`, `curl`, etc can be dropped (possibly even dropping `bash` itself). This one feels like trying to squeeze blood from a stone, though.

**Comment by aguillenv** [comment]
> 1. Run the Next.js build logic for each environment (and twice for `local` with and without telemetry enabled) and copy them into different directories running only the production build that matches the selected environment. Can reduce the amount of modules in `node_modules` and `node_modules` can be symlinked between all of them, which should make space usage a bit lower and speed up time-to-start for the dashboard at the cost of build complexity.

Thinking about this point there's an issue with the UUID since it needs to be generated on the flight per run... I had another idea, which is making the build of the nextjs project in the same docker entry point script in parallel with the postgres init. In my machine, the nextjs build seems to be done in ~20 to 30s so I think both are compatible and we would not need to create unnecessary bundles per environment. This would not reduce the docker container size though but might fix the auth0 app and production experience with the dashboard.

**Comment by aguillenv** [comment]
I have managed to pass env vars after building the dashboard. The env vars are available on the server side always, so on init of the dashboard we request the values and render accordingly.
