### ISSUE TITLE
Export buttons in dashboard don't work

### ISSUE THREAD

**Issue by mtp1376** [iasql/iasql#2070]
Both export buttons don't work:

<img src="https://user-images.githubusercontent.com/5357435/221800748-5451ee42-a574-4fa4-8333-3f94fe2a36e9.png"  width="400">

<img src="https://user-images.githubusercontent.com/5357435/221800801-f7d1445b-b478-48ed-a2d3-01fd379e8397.png"  width="400">

<img src="https://user-images.githubusercontent.com/5357435/221800949-915adf4c-b787-4f1e-99d0-14e345c64f3d.png"  width="400">

**Comment by aguillenv** [comment]
I can see the URL is wrong, we may not be passing the `backendUrl` variable correctly to that method!
