### ISSUE TITLE
Metric alarm db.create error

### ISSUE THREAD

**Issue by aguillenv** [iasql/iasql#2072]
![Image](https://user-images.githubusercontent.com/5898639/221890186-002eb1c0-7455-4fb7-88d3-0d8d8f44cb6e.png)

**Comment by dfellis** [comment]
Wow. How did that get by the test suite?

**Comment by aguillenv** [comment]
I guess this can happen in all the tables we have supporting integers. Maybe we should define globally the [integer constant for psotgres](https://www.postgresql.org/docs/current/datatype-numeric.html) (not sure if we can get them programmatically) and then in every `Mapper` check if the cloud object is in the valid range otherwise return `undefined` and ignore it?

**Comment by yrobla** [comment]
i would not actually hide those values because it will actually hide other edge cases caused by users, that we did not cover in our tests. Instead i would capture those errors as they come, and do the proper fixing of data types

**Comment by aguillenv** [comment]
This is already solved, right? let's link the PR and close it!

**Comment by depombo** [comment]
I think the automated mechanism in the branch/PR name that Yolanda used to link PRs and tasks no longer works?
