### ISSUE TITLE
Schema in query sidebar not overflowing correctly

### ISSUE THREAD

**Issue by aguillenv** [iasql/iasql#2073]
Column names and properties are not x-overflowing properly.

![Image](https://user-images.githubusercontent.com/5898639/221893242-6a4c6658-11b0-4883-8dad-53d370145e6f.png)

**Comment by aguillenv** [comment]
Seen in firefox. Confirm safari and chrome works fine.

**Comment by yrobla** [comment]
happens for me with chrome as well:

<img width="574" alt="image" src="https://user-images.githubusercontent.com/2530861/223407744-6f3fc801-be6e-496d-9554-97cd64c71bea.png">
