### ISSUE TITLE
Empty response message after running insert/update query

### ISSUE THREAD

**Issue by aguillenv** [iasql/iasql#2074]
![Image](https://user-images.githubusercontent.com/5898639/221895313-c17ed398-6576-4540-95c5-08cbc8fe08ad.png)

**Comment by mtp1376** [comment]
What is the expected behavior in this case?

**Comment by aguillenv** [comment]
> What is the expected behavior in this case?

should be just showing the table with the insert/update statement, that `Empty response` label should not be there. Not exactly sure what could be happening there.

**Comment by yrobla** [comment]
Issue here is that code 
```      {!!queryRes &&
        queryRes instanceof Array &&
        (queryRes[0]?.result ?? []) instanceof Array &&
        queryRes.filter((r: any) => (r.result ?? []).length > 0).length === 0 && (
          <Label>Empty response</Label>
        )}
```

So actually as the INSERT does not return any results, it is displaying that label.

**Comment by aguillenv** [comment]
> Issue here is that code
> 
> ```
>         queryRes instanceof Array &&
>         (queryRes[0]?.result ?? []) instanceof Array &&
>         queryRes.filter((r: any) => (r.result ?? []).length > 0).length === 0 && (
>           <Label>Empty response</Label>
>         )}
> ```
> 
> So actually as the INSERT does not return any results, it is displaying that label.

But the table with the statement executed is not the `queryRes`?
