### ISSUE TITLE
Rate limit rage clicking

### ISSUE THREAD

**Issue by depombo** [iasql/iasql#2115]

**Comment by aguillenv** [comment]
![](https://media.tenor.com/images/88eb7114fe68416d13be491222096bf0/tenor.gif)

**Comment by aguillenv** [comment]
![](https://giphy.com/gifs/click-mondays-muffin-and-nuts-Hr2rEQlFrDpCFu9Qt0)

**Comment by aguillenv** [comment]
![](https://media4.giphy.com/media/zCpYQh5YVhdI1rVYpE/giphy.gif?cid=ecf05e471qkss6j10dvblew0ybbt90ay23bg7suv6queu5z8&rid=giphy.gif&ct=g)

**Comment by depombo** [comment]
> ![](https://camo.githubusercontent.com/59dfd2578b98130403ada62a0b7d89818c45775c9852bd2ffb69a6db16e83a24/68747470733a2f2f6d65646961342e67697068792e636f6d2f6d656469612f7a43705951683559566864493172565970452f67697068792e6769663f6369643d656366303565343731716b7373366a31306476626c657730796262743930617932336267377375763671756575357a38267269643d67697068792e6769662663743d67)

I prefer this one or the bunny personally
