### ISSUE TITLE
Use icons to indicate data type in Schema tab

### ISSUE THREAD

**Issue by depombo** [iasql/iasql#2167]
Inspired by Plato

![Image](https://user-images.githubusercontent.com/2381303/224082381-aacf6ec0-cffe-45ef-b916-95a5c64691ef.png)

the screenshot here has some interesting UX improvements we could look into for our dashboard, particularly the title row. The various icons indicating the type of the row and/or if it is an index or foreign key. We could change the Schema tab to use those icons instead of printing the exact type of the column name, and  make hovering over the icon display the type name (similar to how column names that don't fit get the hover behavior right now). This would make the schema tab less "messy"

**Comment by mtp1376** [comment]
For the table results we can't do this as we can for the schema. For the schema we can simply query Postgres's `information_schema` table to find out the type of that column:
```sql
select c.table_name, c.data_type
from information_schema.columns as c
```
But for the query results, I don't think if we have the type of the result without doing extra "magic" work. The thing Plato app is doing is showing those types for the tables, not for the query results.

**Comment by dfellis** [comment]
> For the table results we can't do this as we can for the schema. For the schema we can simply query Postgres's `information_schema` table to find out the type of that column:
> 
> ```sql
> select c.table_name, c.data_type
> from information_schema.columns as c
> ```
> 
> But for the query results, I don't think if we have the type of the result without doing extra "magic" work. The thing Plato app is doing is showing those types for the tables, not for the query results.

The types are given to us by the Postgres client library. We currently just ignore that metadata in the response.
