### ISSUE TITLE
Change `iasql_get_sql_since` signature to accept Postgres date instead of `text`

### ISSUE THREAD

**Issue by depombo** [iasql/iasql#2177]
Currently we have to do

```sql
SELECT * FROM iasql_get_sql_since((now() - interval '2 hours')::text);
 ```

we should add another helper function to take whatever this type is and coerce it to text for the user if Postgres is not?

**Comment by aguillenv** [comment]
this was an issue since our RPCs only accepted `string`s but after @mtp1376 work letting us customize the input for the RPCs this can accept the time field directly
