### ISSUE TITLE
Replace deprecated `set-output` command with environment file

### ISSUE THREAD

**Issue by jongwooo** [iasql/iasql#2187]
## Description

In workflow, `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information, see: [https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/)

**Comment by depombo** [comment]
Hi @jongwooo, thanks for flagging this and contributing to IaSQL! Currently, our test CI suite runs integration tests against real AWS accounts and those credentials are secrets that live within our repo and forks do not have access to them. Let me think some more and talk to the rest of the team to see how we can best move forward here. We will get back to you within 24 hours!
