### ISSUE TITLE
Add high level cloud architecture diagram + advanced configuration to IaSQL on EC2 post

### ISSUE THREAD

**Issue by depombo** [iasql/iasql#2211]
- Add ELB for SSL certificate
- Add ACM certificate
- Add Route53 entry for domain
- Maybe add EBS volume
- Diagram like https://www.reddit.com/r/webdev/comments/zpsseu/my_saas_architecture_tech_stack_on_aws_as_a_solo/

**Comment by mtp1376** [comment]
![Production drawio](https://user-images.githubusercontent.com/5357435/225622072-1a9e6223-e060-4db1-9a6c-d4e8d4ef80c7.png)
