### ISSUE TITLE
`CONTRIBUTING.MD` ToC is obsolete

### ISSUE THREAD

**Issue by mtp1376** [iasql/iasql#2233]

**Comment by depombo** [comment]
What do you mean by this? There are parts that still seem relevant?

**Comment by mtp1376** [comment]
> What do you mean by this? There are parts that still seem relevant?

Updated the title. For example ToC refers to "apply and sync Behavior" which is not relevant currently.

**Comment by depombo** [comment]
Ah I see. There is native ToC that stays up to date in the GitHub UI. Maybe we just delete the ToC? Thoughts @dfellis @aguillenv ?

**Comment by aguillenv** [comment]
I do not follow this sentence "There is native ToC that stays up to date in the GitHub UI". This task should just update the ToC, right? Or are you suggesting we remove it because Github UI can give us something?

**Comment by depombo** [comment]
> Or are you suggesting we remove it because Github UI can give us something?

I am suggesting this. That way we don't have to keep it up to date
