### ISSUE TITLE
Feedback / Wishlist

### ISSUE THREAD

**Issue by W7T2A** [iasql/iasql#770]
# General Feedback
* Renaming table names to be more related to underlying AWS service e.g.:
  *  instance --> ec2_instance
  *  listener --> ec2_lb_listener
  * resource_record_set --> r53_resource_record_set or route53_resource_record_set

After I got some feedback from my dev team I'm working with, who had a first look at how iasql tables are structured, they was a bit confused on first glance at the tables to figure out which table represent / is related to the underlying aws service.

* Support importing tags on resources as jsonb (@depombo already opened issue for this one #769)

# EC2
* Column "Name" should represent Name tag instead of instance-id - instance-id already got it's one column (instance_id)
* Support importing private IP
* Support importing public IP (if available)
  * Would be great if you can import IPv4 as well as IPv6
* Add Elastic-IPs as additional table and show relation to instances if EIP is attached to instance (should overwrite public ip column)
* Add column for architecture type based on instance-type (arm64/x86_64)
* Add state column (running, stopped, hibernated, etc.) of current state of instance
* Add current availability zone the instance is running in
* Add start time / bootstrap time of instance so you can query based on timestamp of start time
* Maybe add column for flag instance if instance is spot-instance (?)
* Add flag if EC2 instance is member of ASG group
* Add some column for information about Memory/CPU related to instance-type (Would be nice to see e.g. t4g.nano got 2cpus, 512mb mem) so you can have a simple overview for non deep aws guys always have to query ec2 instance docs

Especially adding the network related columns to the instances would be great for querying iasql database via shell script or any other script to get ip address for external systems or for managing route53 resources by just query instance/network table(s).
So e.g instance does not have to register itself in route53 - you can manage everything in iasql tables which would be really neat.
I guess if instance is part of an ASG or spot-instance it would be better to make them kind of "read-only" cause aws handling whole lifecycle so I don't know if this will cause some issue when you update instance via iasql (?)

I know most of the bullets are more cosmetic and non related to deploy infrastructure but the strong combination of some reporting features as well as managing the infrastructure is imho the most awesome feature of iasql so you don't need any additional tools and can use power of sql (especially postgres).

# EBS
* Support importing EBS and show relation between EC2 and EBS

Just have an whole overview of an ec2 instance so you could also increase volume size (?)

# EC2 Load-Balancing / Target-Groups
* Add support for adding instances to target groups
* Add support for see relation between instances and which target group they are currently assigned to

Same as network information for deployment script e.g. remove instance from target-group while deployment is running etc. Currently we're using some awscli script for that use case.

# Lambda
* Support Lambda (Already opened #638)

# Pricing (estimated)
* Maybe add some estimated prices for currently running infrastructure (represent current on-demand pricing) 

E.g. [gcpinstances.info](https://gcpinstances.info)
It would be cool to see e.g. for RDS/EC2 what the current instance-types cost in respect of current on-demand pricing so you can have a look at what's the estimated price you have to pay when using this instance (really helpful to create simple report and see some basic pricing information at first glance)

If I receive any further feedback or can contribute any further points I would add that here accordingly.

**Comment by depombo** [comment]
Most of these have been added so closing for now. Thanks again for the detailed explanation Felix!
