### ISSUE TITLE
Full CI/CD for deploys

### ISSUE THREAD

**Issue by depombo** [iasql/iasql#937]
If CI/CD staging + tutorials succeeds go through with a deploy to production

**Comment by ajejoseph22** [comment]
I have added a comment here https://github.com/iasql/iasql-on-iasql/pull/98#issuecomment-1243782443

Would appreciate your input @dfellis @depombo

**Comment by depombo** [comment]
This has been deprioritized now that the onboarding focus on running IaSQL locally
